stages:
  - build
  - release

image: docker:stable

services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - export CURRENT_IMAGE_NAME="$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  - export RELEASE_IMAGE_NAME="$CI_REGISTRY_IMAGE:latest"
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

build:image:
  stage: build
  script:
    - docker build -t "$CURRENT_IMAGE_NAME" .
    - docker images
    - docker push "$CURRENT_IMAGE_NAME"

lint:
  stage: build
  image: $CI_REGISTRY/django-mobans/lint-image
  before_script: []
  script: coala --ci

release:image:
  stage: release
  script:
    - docker pull "$CURRENT_IMAGE_NAME"
    - docker tag "$CURRENT_IMAGE_NAME" "$RELEASE_IMAGE_NAME"
    - docker push "$RELEASE_IMAGE_NAME"
  only:
    - master
